{
 "title": "Mercedes Vehicle Monitoring",
 "tags": [
  "mercedes",
  "vehicle"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "vin",
    "label": "VIN",
    "query": {
     "query": "label_values(last_update_timestamp_seconds, vin)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stream_connected", "legendFormat": " " }
   ]
  },
  {
   "title": "Overall range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "expr": "overallRange{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "AdBlue range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "expr": "rangeAdBlue{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Ignition",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ignitionstate{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_update_timestamp_seconds{vin=\"$vin\"} * 1000"
    }
   ]
  },
  {
   "title": "Current data age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - last_update_timestamp_seconds{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Maximum data age last 24h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time((time() - last_update_timestamp_seconds{vin=\"$vin\"})[24h:15s])"
    }
   ]
  },
  {
   "title": "Parking brake",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "parkbrakestatus{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Fuel tank level",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tanklevelpercent{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "AdBlue level",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tankLevelAdBlue{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Vehicle lock status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "doorlockstatusvehicle{vin=\"$vin\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "overallRange{vin=\"$vin\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rangeAdBlue{vin=\"$vin\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Vehicle trip since start", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Trip started at",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\n  max_over_time(\r\n    (timestamp(idelta({__name__=~\"distanceStart\", vin=\"$vin\"}[5m]) < 0))[30d:15s]\r\n  )\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driven time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drivenTimeStart{vin=\"$vin\"} / 60"
    }
   ]
  },
  {
   "title": "Fuel consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidconsumptionstart{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Fuel used since start",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "distanceStart{vin=\"$vin\"} * liquidconsumptionstart{vin=\"$vin\"} / 100"
    }
   ]
  },
  {
   "title": "Speed over last 2 minutes (estimate)",
   "type": "timeseries",
   "description": "Calculated from the change in distanceStart over the previous two minutes.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kmh" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (clamp_min(delta(distanceStart{vin=\"$vin\"}[2m]) * 30, 0))[2m:10s]\r\n)"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "distanceStart{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Average speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "averageSpeedStart{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Vehicle trip reset manually by driver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Average speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "averageSpeedReset{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "distanceReset{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Fuel consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidconsumptionreset{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Driven time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drivenTimeReset{vin=\"$vin\"} / 60"
    }
   ]
  },
  {
   "title": "Fuel used since reset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "liters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "distanceReset{vin=\"$vin\"} * liquidconsumptionreset{vin=\"$vin\"} / 100"
    }
   ]
  },
  { "title": "Doors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Front right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorstatusfrontright{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Front left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorstatusfrontleft{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Rear left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorstatusrearleft{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Rear right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorstatusrearright{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Engine hood",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engineHoodStatus{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Trunk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "decklidstatus{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Trunk lock",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorlockstatusdecklid{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Front right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorlockstatusfrontright{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Front left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorlockstatusfrontleft{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Rear left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorlockstatusrearleft{vin=\"$vin\"}"
    }
   ]
  },
  {
   "title": "Rear right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "doorlockstatusrearright{vin=\"$vin\"}"
    }
   ]
  },
  { "title": "Percentage history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "AdBlue level history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tankLevelAdBlue{vin=\"$vin\"}",
     "legendFormat": "AdBlue"
    }
   ]
  },
  {
   "title": "Fuel tank level history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tanklevelpercent{vin=\"$vin\"}",
     "legendFormat": "Fuel tank"
    }
   ]
  },
  {
   "title": "Overall range history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "expr": "overallRange{vin=\"$vin\"}",
     "legendFormat": "Overall range"
    }
   ]
  },
  {
   "title": "Tire pressure history",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "tirepressureFrontLeft{vin=\"$vin\"} / 100",
     "legendFormat": "Front left"
    },
    {
     "expr": "tirepressureFrontRight{vin=\"$vin\"} / 100",
     "legendFormat": "Front right"
    },
    {
     "expr": "tirepressureRearLeft{vin=\"$vin\"} / 100",
     "legendFormat": "Rear left"
    },
    {
     "expr": "tirepressureRearRight{vin=\"$vin\"} / 100",
     "legendFormat": "Rear right"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "odo{vin=\"$vin\"}",
     "legendFormat": "odometer"
    }
   ]
  }
 ]
}